-- =========================================================
-- FORMA CLOTHING STORE - SUPABASE DATABASE SCHEMA
-- Paste and Run this script in the Supabase SQL Editor
-- =========================================================

-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    currency TEXT DEFAULT 'LKR',
    formatted_price TEXT,
    tag TEXT,
    image TEXT NOT NULL,
    hover_image TEXT,
    colorways JSONB,
    description TEXT,
    sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L'],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    items JSONB NOT NULL,
    customer_email TEXT NOT NULL,
    customer_name TEXT,
    shipping_address TEXT,
    total NUMERIC(10, 2) NOT NULL,
    status TEXT DEFAULT 'Confirmed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Users Profile Table (for demo authentication)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    role TEXT DEFAULT 'customer',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS) & Allow public read access
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on products"
    ON public.products FOR SELECT
    USING (true);

CREATE POLICY "Allow all access on products for anon/service"
    ON public.products FOR ALL
    USING (true);

CREATE POLICY "Allow insert orders"
    ON public.orders FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Allow select orders"
    ON public.orders FOR SELECT
    USING (true);

CREATE POLICY "Allow all on profiles"
    ON public.profiles FOR ALL
    USING (true);

-- 5. Seed Initial Products Data
INSERT INTO public.products (slug, name, category, price, currency, formatted_price, tag, image, hover_image, colorways, description, sizes)
VALUES
(
    'leaguerun-crew-neck',
    'LeagueRun Crew Neck',
    'Men',
    4450.00,
    'LKR',
    'LKR 4,450.00',
    'New',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8993_c94490be-8596-478c-992a-9d55a5235d67.jpg?v=1787891748',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8995_7ec38730-c22e-4db7-90a5-71d6330c5aac.jpg?v=1787891814',
    '[
      {"colorName": "White/Navy", "swatchColors": ["#1b2d4f", "#e6ecf2"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8993_c94490be-8596-478c-992a-9d55a5235d67.jpg?v=1787891748", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8995_7ec38730-c22e-4db7-90a5-71d6330c5aac.jpg?v=1787891814"},
      {"colorName": "Navy/White", "swatchColors": ["#f5f5f5", "#1b2d4f"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9038.jpg?v=1787891205", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9039.jpg?v=1787891814"}
    ]'::jsonb,
    'Easy in feel but strong in presence, combines a loose athletic silhouette with sharp two-tone detailing. Finished with statement branding.',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL']
),
(
    'leaguerun-baby-tee',
    'LeagueRun Baby Tee',
    'Women',
    3750.00,
    'LKR',
    'LKR 3,750.00',
    'Bestseller',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9033.jpg?v=1787736560',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9030_b4dedbbc-c106-4034-9162-2be0653ce696.jpg?v=1787736607',
    '[
      {"colorName": "Maroon/White", "swatchColors": ["#681a2c", "#f0f0f0"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9033.jpg?v=1787736560", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9030_b4dedbbc-c106-4034-9162-2be0653ce696.jpg?v=1787736607"},
      {"colorName": "White/Navy", "swatchColors": ["#ffffff", "#1b2d4f"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9055_121bc314-44b5-4ea5-8c58-3064f63ed344.jpg?v=1787736500", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9054_3b95d72e-db49-40f6-b1f6-2b7a4a08031f.jpg?v=1787736607"}
    ]'::jsonb,
    'Form-fitting cropped baby tee with raglan sleeves and athletic contrast collar.',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL']
),
(
    'leaguerun-tank',
    'LeagueRun Tank',
    'Men',
    4450.00,
    'LKR',
    'LKR 4,450.00',
    'Trending',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9012_731e69f2-d488-47cb-99cf-6977745487eb.jpg?v=1787735661',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9009_d5c74255-9442-443c-898f-5794d488a018.jpg?v=1787735771',
    '[
      {"colorName": "Grey/White", "swatchColors": ["#e4e4e7", "#1b2d4f"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9012_731e69f2-d488-47cb-99cf-6977745487eb.jpg?v=1787735661", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_9009_d5c74255-9442-443c-898f-5794d488a018.jpg?v=1787735771"},
      {"colorName": "White/Navy", "swatchColors": ["#ffffff", "#1b2d4f"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8959_0c879d61-7770-477e-bf12-bf1276fb0402.jpg?v=1787735704", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8957_b535421f-b214-4996-acbe-9b4bd347ae01.jpg?v=1787735771"}
    ]'::jsonb,
    'Relaxed sleeveless silhouette with contrast shoulder detailing and deep cut armholes.',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL']
),
(
    'gx-tee',
    'GX Tee',
    'Men',
    4450.00,
    'LKR',
    'LKR 4,450.00',
    'Trending',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8490_7c13b2df-fc3f-41c2-a898-42103aac93ae.jpg?v=1787734609',
    'https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8475_ca06f8db-b439-481f-82df-b91ff9f54ff0.jpg?v=1787734832',
    '[
      {"colorName": "Jet Black", "swatchColors": ["#141414", "#dedede"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8490_7c13b2df-fc3f-41c2-a898-42103aac93ae.jpg?v=1787734609", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8475_ca06f8db-b439-481f-82df-b91ff9f54ff0.jpg?v=1787734832"},
      {"colorName": "Sheer White", "swatchColors": ["#f8f9fa", "#141414"], "primaryImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8461.jpg?v=1787734730", "hoverImage": "https://cdn.shopify.com/s/files/1/0607/0619/3614/files/IMG_8451_05e06504-ccba-451c-9812-0aa624daf80b.jpg?v=1787734832"}
    ]'::jsonb,
    'Heavyweight oversized streetwear tee featuring high-density graphic print across the back.',
    ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL']
)
ON CONFLICT (slug) DO NOTHING;
